uploads = []
generated = []

[[outputs]]
id = "hZXlCMBWKDuFtxu4DtYtT"
uri = "file://solarepc-deploy.tar.gz"
type = "unspecified"
title = "solarepc-deploy.tar.gz — includes git-deploy, git-pull, git-reset"
