import type { SelectOption } from "@/components/ui/searchable-select";

// ── Indian Banks ──────────────────────────────────────────────────────────────
export const INDIAN_BANKS: SelectOption[] = [
  // Public Sector Banks
  { value: "State Bank of India",           label: "State Bank of India",           sub: "PSB · SBI" },
  { value: "Punjab National Bank",          label: "Punjab National Bank",          sub: "PSB · PNB" },
  { value: "Bank of Baroda",                label: "Bank of Baroda",                sub: "PSB · BOB" },
  { value: "Canara Bank",                   label: "Canara Bank",                   sub: "PSB" },
  { value: "Union Bank of India",           label: "Union Bank of India",           sub: "PSB" },
  { value: "Bank of India",                 label: "Bank of India",                 sub: "PSB · BOI" },
  { value: "Indian Bank",                   label: "Indian Bank",                   sub: "PSB" },
  { value: "Central Bank of India",         label: "Central Bank of India",         sub: "PSB" },
  { value: "Indian Overseas Bank",          label: "Indian Overseas Bank",          sub: "PSB · IOB" },
  { value: "UCO Bank",                      label: "UCO Bank",                      sub: "PSB" },
  { value: "Bank of Maharashtra",           label: "Bank of Maharashtra",           sub: "PSB" },
  { value: "Punjab and Sind Bank",          label: "Punjab and Sind Bank",          sub: "PSB" },
  // Private Sector Banks
  { value: "HDFC Bank",                     label: "HDFC Bank",                     sub: "Private" },
  { value: "ICICI Bank",                    label: "ICICI Bank",                    sub: "Private" },
  { value: "Axis Bank",                     label: "Axis Bank",                     sub: "Private" },
  { value: "Kotak Mahindra Bank",           label: "Kotak Mahindra Bank",           sub: "Private" },
  { value: "IndusInd Bank",                 label: "IndusInd Bank",                 sub: "Private" },
  { value: "Yes Bank",                      label: "Yes Bank",                      sub: "Private" },
  { value: "IDFC First Bank",               label: "IDFC First Bank",               sub: "Private" },
  { value: "Federal Bank",                  label: "Federal Bank",                  sub: "Private" },
  { value: "RBL Bank",                      label: "RBL Bank",                      sub: "Private" },
  { value: "Bandhan Bank",                  label: "Bandhan Bank",                  sub: "Private" },
  { value: "South Indian Bank",             label: "South Indian Bank",             sub: "Private" },
  { value: "Karur Vysya Bank",              label: "Karur Vysya Bank",              sub: "Private · KVB" },
  { value: "City Union Bank",               label: "City Union Bank",               sub: "Private · CUB" },
  { value: "Tamilnad Mercantile Bank",      label: "Tamilnad Mercantile Bank",      sub: "Private · TMB" },
  { value: "Dhanlaxmi Bank",                label: "Dhanlaxmi Bank",                sub: "Private" },
  { value: "Nainital Bank",                 label: "Nainital Bank",                 sub: "Private" },
  { value: "CSB Bank",                      label: "CSB Bank",                      sub: "Private" },
  // Small Finance Banks
  { value: "AU Small Finance Bank",         label: "AU Small Finance Bank",         sub: "SFB" },
  { value: "Jana Small Finance Bank",       label: "Jana Small Finance Bank",       sub: "SFB" },
  { value: "Ujjivan Small Finance Bank",    label: "Ujjivan Small Finance Bank",    sub: "SFB" },
  { value: "Equitas Small Finance Bank",    label: "Equitas Small Finance Bank",    sub: "SFB" },
  { value: "Suryoday Small Finance Bank",   label: "Suryoday Small Finance Bank",   sub: "SFB" },
  // Payment & Co-operative
  { value: "Paytm Payments Bank",           label: "Paytm Payments Bank",           sub: "Payments Bank" },
  { value: "Airtel Payments Bank",          label: "Airtel Payments Bank",          sub: "Payments Bank" },
  { value: "India Post Payments Bank",      label: "India Post Payments Bank",      sub: "Payments Bank" },
  // Foreign
  { value: "Citibank",                      label: "Citibank",                      sub: "Foreign" },
  { value: "Standard Chartered Bank",       label: "Standard Chartered Bank",       sub: "Foreign" },
  { value: "HSBC Bank",                     label: "HSBC Bank",                     sub: "Foreign" },
  { value: "Deutsche Bank",                 label: "Deutsche Bank",                 sub: "Foreign" },
  { value: "DBS Bank",                      label: "DBS Bank",                      sub: "Foreign" },
];

// ── Bank Account Types ────────────────────────────────────────────────────────
export const ACCOUNT_TYPES: SelectOption[] = [
  { value: "Current",           label: "Current Account",         sub: "For businesses & firms" },
  { value: "Savings",           label: "Savings Account",         sub: "Individual / personal" },
  { value: "Cash Credit",       label: "Cash Credit (CC)",        sub: "Working capital facility" },
  { value: "Overdraft",         label: "Overdraft (OD)",          sub: "Credit against assets" },
  { value: "NRE",               label: "NRE Account",             sub: "Non-Resident External (INR)" },
  { value: "NRO",               label: "NRO Account",             sub: "Non-Resident Ordinary" },
  { value: "FCNR",              label: "FCNR Account",            sub: "Foreign Currency Non-Resident" },
  { value: "Fixed Deposit",     label: "Fixed Deposit (FD)",      sub: "Term deposit" },
  { value: "Recurring Deposit", label: "Recurring Deposit (RD)",  sub: "Monthly instalment deposit" },
];

// ── Indian States & Union Territories ────────────────────────────────────────
export const INDIAN_STATES: SelectOption[] = [
  // 28 States
  { value: "Andhra Pradesh",     label: "Andhra Pradesh",     sub: "State" },
  { value: "Arunachal Pradesh",  label: "Arunachal Pradesh",  sub: "State" },
  { value: "Assam",              label: "Assam",              sub: "State" },
  { value: "Bihar",              label: "Bihar",              sub: "State" },
  { value: "Chhattisgarh",       label: "Chhattisgarh",       sub: "State" },
  { value: "Goa",                label: "Goa",                sub: "State" },
  { value: "Gujarat",            label: "Gujarat",            sub: "State" },
  { value: "Haryana",            label: "Haryana",            sub: "State" },
  { value: "Himachal Pradesh",   label: "Himachal Pradesh",   sub: "State" },
  { value: "Jharkhand",          label: "Jharkhand",          sub: "State" },
  { value: "Karnataka",          label: "Karnataka",          sub: "State" },
  { value: "Kerala",             label: "Kerala",             sub: "State" },
  { value: "Madhya Pradesh",     label: "Madhya Pradesh",     sub: "State" },
  { value: "Maharashtra",        label: "Maharashtra",        sub: "State" },
  { value: "Manipur",            label: "Manipur",            sub: "State" },
  { value: "Meghalaya",          label: "Meghalaya",          sub: "State" },
  { value: "Mizoram",            label: "Mizoram",            sub: "State" },
  { value: "Nagaland",           label: "Nagaland",           sub: "State" },
  { value: "Odisha",             label: "Odisha",             sub: "State" },
  { value: "Punjab",             label: "Punjab",             sub: "State" },
  { value: "Rajasthan",          label: "Rajasthan",          sub: "State" },
  { value: "Sikkim",             label: "Sikkim",             sub: "State" },
  { value: "Tamil Nadu",         label: "Tamil Nadu",         sub: "State" },
  { value: "Telangana",          label: "Telangana",          sub: "State" },
  { value: "Tripura",            label: "Tripura",            sub: "State" },
  { value: "Uttar Pradesh",      label: "Uttar Pradesh",      sub: "State" },
  { value: "Uttarakhand",        label: "Uttarakhand",        sub: "State" },
  { value: "West Bengal",        label: "West Bengal",        sub: "State" },
  // 8 Union Territories
  { value: "Andaman and Nicobar Islands",                  label: "Andaman and Nicobar Islands",                  sub: "UT" },
  { value: "Chandigarh",                                   label: "Chandigarh",                                   sub: "UT" },
  { value: "Dadra and Nagar Haveli and Daman and Diu",     label: "Dadra and Nagar Haveli and Daman and Diu",     sub: "UT" },
  { value: "Delhi",                                        label: "Delhi (NCT)",                                  sub: "UT" },
  { value: "Jammu and Kashmir",                            label: "Jammu and Kashmir",                            sub: "UT" },
  { value: "Ladakh",                                       label: "Ladakh",                                       sub: "UT" },
  { value: "Lakshadweep",                                  label: "Lakshadweep",                                  sub: "UT" },
  { value: "Puducherry",                                   label: "Puducherry",                                   sub: "UT" },
];

// ── Major Indian Cities ───────────────────────────────────────────────────────
export const INDIAN_CITIES: SelectOption[] = [
  { value: "Mumbai",              label: "Mumbai",              sub: "Maharashtra" },
  { value: "Delhi",               label: "Delhi",               sub: "Delhi NCT" },
  { value: "Bengaluru",           label: "Bengaluru",           sub: "Karnataka" },
  { value: "Hyderabad",           label: "Hyderabad",           sub: "Telangana" },
  { value: "Ahmedabad",           label: "Ahmedabad",           sub: "Gujarat" },
  { value: "Chennai",             label: "Chennai",             sub: "Tamil Nadu" },
  { value: "Kolkata",             label: "Kolkata",             sub: "West Bengal" },
  { value: "Surat",               label: "Surat",               sub: "Gujarat" },
  { value: "Pune",                label: "Pune",                sub: "Maharashtra" },
  { value: "Jaipur",              label: "Jaipur",              sub: "Rajasthan" },
  { value: "Lucknow",             label: "Lucknow",             sub: "Uttar Pradesh" },
  { value: "Kanpur",              label: "Kanpur",              sub: "Uttar Pradesh" },
  { value: "Nagpur",              label: "Nagpur",              sub: "Maharashtra" },
  { value: "Indore",              label: "Indore",              sub: "Madhya Pradesh" },
  { value: "Thane",               label: "Thane",               sub: "Maharashtra" },
  { value: "Bhopal",              label: "Bhopal",              sub: "Madhya Pradesh" },
  { value: "Visakhapatnam",       label: "Visakhapatnam",       sub: "Andhra Pradesh" },
  { value: "Patna",               label: "Patna",               sub: "Bihar" },
  { value: "Vadodara",            label: "Vadodara",            sub: "Gujarat" },
  { value: "Ghaziabad",           label: "Ghaziabad",           sub: "Uttar Pradesh" },
  { value: "Ludhiana",            label: "Ludhiana",            sub: "Punjab" },
  { value: "Agra",                label: "Agra",                sub: "Uttar Pradesh" },
  { value: "Nashik",              label: "Nashik",              sub: "Maharashtra" },
  { value: "Faridabad",           label: "Faridabad",           sub: "Haryana" },
  { value: "Meerut",              label: "Meerut",              sub: "Uttar Pradesh" },
  { value: "Rajkot",              label: "Rajkot",              sub: "Gujarat" },
  { value: "Varanasi",            label: "Varanasi",            sub: "Uttar Pradesh" },
  { value: "Srinagar",            label: "Srinagar",            sub: "J&K" },
  { value: "Aurangabad",          label: "Aurangabad",          sub: "Maharashtra" },
  { value: "Dhanbad",             label: "Dhanbad",             sub: "Jharkhand" },
  { value: "Amritsar",            label: "Amritsar",            sub: "Punjab" },
  { value: "Navi Mumbai",         label: "Navi Mumbai",         sub: "Maharashtra" },
  { value: "Prayagraj",           label: "Prayagraj",           sub: "Uttar Pradesh" },
  { value: "Ranchi",              label: "Ranchi",              sub: "Jharkhand" },
  { value: "Howrah",              label: "Howrah",              sub: "West Bengal" },
  { value: "Coimbatore",          label: "Coimbatore",          sub: "Tamil Nadu" },
  { value: "Jabalpur",            label: "Jabalpur",            sub: "Madhya Pradesh" },
  { value: "Gwalior",             label: "Gwalior",             sub: "Madhya Pradesh" },
  { value: "Vijayawada",          label: "Vijayawada",          sub: "Andhra Pradesh" },
  { value: "Jodhpur",             label: "Jodhpur",             sub: "Rajasthan" },
  { value: "Madurai",             label: "Madurai",             sub: "Tamil Nadu" },
  { value: "Raipur",              label: "Raipur",              sub: "Chhattisgarh" },
  { value: "Kota",                label: "Kota",                sub: "Rajasthan" },
  { value: "Guwahati",            label: "Guwahati",            sub: "Assam" },
  { value: "Chandigarh",          label: "Chandigarh",          sub: "UT" },
  { value: "Solapur",             label: "Solapur",             sub: "Maharashtra" },
  { value: "Hubli-Dharwad",       label: "Hubli-Dharwad",       sub: "Karnataka" },
  { value: "Mysuru",              label: "Mysuru",              sub: "Karnataka" },
  { value: "Tiruchirappalli",     label: "Tiruchirappalli",     sub: "Tamil Nadu" },
  { value: "Bareilly",            label: "Bareilly",            sub: "Uttar Pradesh" },
  { value: "Aligarh",             label: "Aligarh",             sub: "Uttar Pradesh" },
  { value: "Tiruppur",            label: "Tiruppur",            sub: "Tamil Nadu" },
  { value: "Moradabad",           label: "Moradabad",           sub: "Uttar Pradesh" },
  { value: "Jalandhar",           label: "Jalandhar",           sub: "Punjab" },
  { value: "Bhubaneswar",         label: "Bhubaneswar",         sub: "Odisha" },
  { value: "Salem",               label: "Salem",               sub: "Tamil Nadu" },
  { value: "Warangal",            label: "Warangal",            sub: "Telangana" },
  { value: "Guntur",              label: "Guntur",              sub: "Andhra Pradesh" },
  { value: "Kochi",               label: "Kochi",               sub: "Kerala" },
  { value: "Thiruvananthapuram",  label: "Thiruvananthapuram",  sub: "Kerala" },
  { value: "Kozhikode",           label: "Kozhikode",           sub: "Kerala" },
  { value: "Mangaluru",           label: "Mangaluru",           sub: "Karnataka" },
  { value: "Udaipur",             label: "Udaipur",             sub: "Rajasthan" },
  { value: "Tirunelveli",         label: "Tirunelveli",         sub: "Tamil Nadu" },
  { value: "Jamshedpur",          label: "Jamshedpur",          sub: "Jharkhand" },
  { value: "Belagavi",            label: "Belagavi",            sub: "Karnataka" },
  { value: "Noida",               label: "Noida",               sub: "Uttar Pradesh" },
  { value: "Gurugram",            label: "Gurugram",            sub: "Haryana" },
  { value: "Dehradun",            label: "Dehradun",            sub: "Uttarakhand" },
  { value: "Shimla",              label: "Shimla",              sub: "Himachal Pradesh" },
  { value: "Jammu",               label: "Jammu",               sub: "J&K" },
  { value: "Puducherry",          label: "Puducherry",          sub: "UT" },
  { value: "Panaji",              label: "Panaji",              sub: "Goa" },
  { value: "Imphal",              label: "Imphal",              sub: "Manipur" },
  { value: "Shillong",            label: "Shillong",            sub: "Meghalaya" },
  { value: "Agartala",            label: "Agartala",            sub: "Tripura" },
  { value: "Itanagar",            label: "Itanagar",            sub: "Arunachal Pradesh" },
  { value: "Dispur",              label: "Dispur",              sub: "Assam" },
  { value: "Gangtok",             label: "Gangtok",             sub: "Sikkim" },
  { value: "Kohima",              label: "Kohima",              sub: "Nagaland" },
  { value: "Aizawl",              label: "Aizawl",              sub: "Mizoram" },
];

// ── Countries (India first, then alphabetical) ────────────────────────────────
export const COUNTRIES: SelectOption[] = [
  { value: "India",                label: "🇮🇳 India",                sub: "Default" },
  { value: "Afghanistan",          label: "Afghanistan" },
  { value: "Australia",            label: "🇦🇺 Australia" },
  { value: "Bahrain",              label: "🇧🇭 Bahrain" },
  { value: "Bangladesh",           label: "🇧🇩 Bangladesh" },
  { value: "Belgium",              label: "🇧🇪 Belgium" },
  { value: "Brazil",               label: "🇧🇷 Brazil" },
  { value: "Canada",               label: "🇨🇦 Canada" },
  { value: "China",                label: "🇨🇳 China" },
  { value: "Denmark",              label: "🇩🇰 Denmark" },
  { value: "Egypt",                label: "🇪🇬 Egypt" },
  { value: "Ethiopia",             label: "Ethiopia" },
  { value: "Finland",              label: "Finland" },
  { value: "France",               label: "🇫🇷 France" },
  { value: "Germany",              label: "🇩🇪 Germany" },
  { value: "Ghana",                label: "Ghana" },
  { value: "Hong Kong",            label: "🇭🇰 Hong Kong" },
  { value: "Indonesia",            label: "🇮🇩 Indonesia" },
  { value: "Iran",                 label: "Iran" },
  { value: "Iraq",                 label: "Iraq" },
  { value: "Ireland",              label: "🇮🇪 Ireland" },
  { value: "Israel",               label: "🇮🇱 Israel" },
  { value: "Italy",                label: "🇮🇹 Italy" },
  { value: "Japan",                label: "🇯🇵 Japan" },
  { value: "Jordan",               label: "Jordan" },
  { value: "Kenya",                label: "Kenya" },
  { value: "Kuwait",               label: "🇰🇼 Kuwait" },
  { value: "Malaysia",             label: "🇲🇾 Malaysia" },
  { value: "Maldives",             label: "Maldives" },
  { value: "Mauritius",            label: "Mauritius" },
  { value: "Mexico",               label: "🇲🇽 Mexico" },
  { value: "Myanmar",              label: "Myanmar" },
  { value: "Nepal",                label: "🇳🇵 Nepal" },
  { value: "Netherlands",          label: "🇳🇱 Netherlands" },
  { value: "New Zealand",          label: "🇳🇿 New Zealand" },
  { value: "Nigeria",              label: "Nigeria" },
  { value: "Norway",               label: "Norway" },
  { value: "Oman",                 label: "🇴🇲 Oman" },
  { value: "Pakistan",             label: "🇵🇰 Pakistan" },
  { value: "Philippines",          label: "🇵🇭 Philippines" },
  { value: "Portugal",             label: "Portugal" },
  { value: "Qatar",                label: "🇶🇦 Qatar" },
  { value: "Russia",               label: "🇷🇺 Russia" },
  { value: "Saudi Arabia",         label: "🇸🇦 Saudi Arabia" },
  { value: "Singapore",            label: "🇸🇬 Singapore" },
  { value: "South Africa",         label: "🇿🇦 South Africa" },
  { value: "South Korea",          label: "🇰🇷 South Korea" },
  { value: "Spain",                label: "🇪🇸 Spain" },
  { value: "Sri Lanka",            label: "🇱🇰 Sri Lanka" },
  { value: "Sweden",               label: "Sweden" },
  { value: "Switzerland",          label: "🇨🇭 Switzerland" },
  { value: "Taiwan",               label: "Taiwan" },
  { value: "Tanzania",             label: "Tanzania" },
  { value: "Thailand",             label: "🇹🇭 Thailand" },
  { value: "Turkey",               label: "🇹🇷 Turkey" },
  { value: "Uganda",               label: "Uganda" },
  { value: "Ukraine",              label: "Ukraine" },
  { value: "United Arab Emirates", label: "🇦🇪 United Arab Emirates" },
  { value: "United Kingdom",       label: "🇬🇧 United Kingdom" },
  { value: "United States",        label: "🇺🇸 United States" },
  { value: "Vietnam",              label: "🇻🇳 Vietnam" },
  { value: "Zambia",               label: "Zambia" },
  { value: "Zimbabwe",             label: "Zimbabwe" },
];
