import type { SelectOption } from "@/components/ui/searchable-select";

// ── GST State Code lookup (state name → 2-digit code) ────────────────────────
export const GST_STATE_CODE_MAP: Record<string, string> = {
  "Jammu and Kashmir":                              "01",
  "Himachal Pradesh":                               "02",
  "Punjab":                                         "03",
  "Chandigarh":                                     "04",
  "Uttarakhand":                                    "05",
  "Haryana":                                        "06",
  "Delhi":                                          "07",
  "Rajasthan":                                      "08",
  "Uttar Pradesh":                                  "09",
  "Bihar":                                          "10",
  "Sikkim":                                         "11",
  "Arunachal Pradesh":                              "12",
  "Nagaland":                                       "13",
  "Manipur":                                        "14",
  "Mizoram":                                        "15",
  "Tripura":                                        "16",
  "Meghalaya":                                      "17",
  "Assam":                                          "18",
  "West Bengal":                                    "19",
  "Jharkhand":                                      "20",
  "Odisha":                                         "21",
  "Chhattisgarh":                                   "22",
  "Madhya Pradesh":                                 "23",
  "Gujarat":                                        "24",
  "Dadra and Nagar Haveli and Daman and Diu":       "26",
  "Maharashtra":                                    "27",
  "Andhra Pradesh":                                 "37",
  "Karnataka":                                      "29",
  "Goa":                                            "30",
  "Lakshadweep":                                    "31",
  "Kerala":                                         "32",
  "Tamil Nadu":                                     "33",
  "Puducherry":                                     "34",
  "Andaman and Nicobar Islands":                    "35",
  "Telangana":                                      "36",
  "Ladakh":                                         "38",
};

// ── GST State Codes — for the State Code combobox ────────────────────────────
export const GST_STATE_CODES: SelectOption[] = [
  { value: "01", label: "01 — Jammu & Kashmir" },
  { value: "02", label: "02 — Himachal Pradesh" },
  { value: "03", label: "03 — Punjab" },
  { value: "04", label: "04 — Chandigarh" },
  { value: "05", label: "05 — Uttarakhand" },
  { value: "06", label: "06 — Haryana" },
  { value: "07", label: "07 — Delhi" },
  { value: "08", label: "08 — Rajasthan" },
  { value: "09", label: "09 — Uttar Pradesh" },
  { value: "10", label: "10 — Bihar" },
  { value: "11", label: "11 — Sikkim" },
  { value: "12", label: "12 — Arunachal Pradesh" },
  { value: "13", label: "13 — Nagaland" },
  { value: "14", label: "14 — Manipur" },
  { value: "15", label: "15 — Mizoram" },
  { value: "16", label: "16 — Tripura" },
  { value: "17", label: "17 — Meghalaya" },
  { value: "18", label: "18 — Assam" },
  { value: "19", label: "19 — West Bengal" },
  { value: "20", label: "20 — Jharkhand" },
  { value: "21", label: "21 — Odisha" },
  { value: "22", label: "22 — Chhattisgarh" },
  { value: "23", label: "23 — Madhya Pradesh" },
  { value: "24", label: "24 — Gujarat" },
  { value: "26", label: "26 — Dadra, Nagar Haveli & Daman and Diu" },
  { value: "27", label: "27 — Maharashtra" },
  { value: "29", label: "29 — Karnataka" },
  { value: "30", label: "30 — Goa" },
  { value: "31", label: "31 — Lakshadweep" },
  { value: "32", label: "32 — Kerala" },
  { value: "33", label: "33 — Tamil Nadu" },
  { value: "34", label: "34 — Puducherry" },
  { value: "35", label: "35 — Andaman & Nicobar Islands" },
  { value: "36", label: "36 — Telangana" },
  { value: "37", label: "37 — Andhra Pradesh" },
  { value: "38", label: "38 — Ladakh" },
  { value: "97", label: "97 — Other Territory" },
  { value: "99", label: "99 — Centre Jurisdiction" },
];

// ── Indian Banks ──────────────────────────────────────────────────────────────
export const INDIAN_BANKS: SelectOption[] = [
  // Public Sector Banks
  { value: "State Bank of India",           label: "State Bank of India",           sub: "PSB · SBI" },
  { value: "Punjab National Bank",          label: "Punjab National Bank",          sub: "PSB · PNB" },
  { value: "Bank of Baroda",                label: "Bank of Baroda",                sub: "PSB · BOB" },
  { value: "Canara Bank",                   label: "Canara Bank",                   sub: "PSB" },
  { value: "Union Bank of India",           label: "Union Bank of India",           sub: "PSB" },
  { value: "Bank of India",                 label: "Bank of India",                 sub: "PSB · BOI" },
  { value: "Indian Bank",                   label: "Indian Bank",                   sub: "PSB" },
  { value: "Central Bank of India",         label: "Central Bank of India",         sub: "PSB" },
  { value: "Indian Overseas Bank",          label: "Indian Overseas Bank",          sub: "PSB · IOB" },
  { value: "UCO Bank",                      label: "UCO Bank",                      sub: "PSB" },
  { value: "Bank of Maharashtra",           label: "Bank of Maharashtra",           sub: "PSB" },
  { value: "Punjab and Sind Bank",          label: "Punjab and Sind Bank",          sub: "PSB" },
  // Private Sector Banks
  { value: "HDFC Bank",                     label: "HDFC Bank",                     sub: "Private" },
  { value: "ICICI Bank",                    label: "ICICI Bank",                    sub: "Private" },
  { value: "Axis Bank",                     label: "Axis Bank",                     sub: "Private" },
  { value: "Kotak Mahindra Bank",           label: "Kotak Mahindra Bank",           sub: "Private" },
  { value: "IndusInd Bank",                 label: "IndusInd Bank",                 sub: "Private" },
  { value: "Yes Bank",                      label: "Yes Bank",                      sub: "Private" },
  { value: "IDFC First Bank",               label: "IDFC First Bank",               sub: "Private" },
  { value: "Federal Bank",                  label: "Federal Bank",                  sub: "Private" },
  { value: "RBL Bank",                      label: "RBL Bank",                      sub: "Private" },
  { value: "Bandhan Bank",                  label: "Bandhan Bank",                  sub: "Private" },
  { value: "South Indian Bank",             label: "South Indian Bank",             sub: "Private" },
  { value: "Karur Vysya Bank",              label: "Karur Vysya Bank",              sub: "Private · KVB" },
  { value: "City Union Bank",               label: "City Union Bank",               sub: "Private · CUB" },
  { value: "Tamilnad Mercantile Bank",      label: "Tamilnad Mercantile Bank",      sub: "Private · TMB" },
  { value: "Dhanlaxmi Bank",                label: "Dhanlaxmi Bank",                sub: "Private" },
  { value: "Nainital Bank",                 label: "Nainital Bank",                 sub: "Private" },
  { value: "CSB Bank",                      label: "CSB Bank",                      sub: "Private" },
  // Small Finance Banks
  { value: "AU Small Finance Bank",         label: "AU Small Finance Bank",         sub: "SFB" },
  { value: "Jana Small Finance Bank",       label: "Jana Small Finance Bank",       sub: "SFB" },
  { value: "Ujjivan Small Finance Bank",    label: "Ujjivan Small Finance Bank",    sub: "SFB" },
  { value: "Equitas Small Finance Bank",    label: "Equitas Small Finance Bank",    sub: "SFB" },
  { value: "Suryoday Small Finance Bank",   label: "Suryoday Small Finance Bank",   sub: "SFB" },
  // Payment & Co-operative
  { value: "Paytm Payments Bank",           label: "Paytm Payments Bank",           sub: "Payments Bank" },
  { value: "Airtel Payments Bank",          label: "Airtel Payments Bank",          sub: "Payments Bank" },
  { value: "India Post Payments Bank",      label: "India Post Payments Bank",      sub: "Payments Bank" },
  // Foreign
  { value: "Citibank",                      label: "Citibank",                      sub: "Foreign" },
  { value: "Standard Chartered Bank",       label: "Standard Chartered Bank",       sub: "Foreign" },
  { value: "HSBC Bank",                     label: "HSBC Bank",                     sub: "Foreign" },
  { value: "Deutsche Bank",                 label: "Deutsche Bank",                 sub: "Foreign" },
  { value: "DBS Bank",                      label: "DBS Bank",                      sub: "Foreign" },
];

// ── Bank Account Types ────────────────────────────────────────────────────────
export const ACCOUNT_TYPES: SelectOption[] = [
  { value: "Current",           label: "Current Account",         sub: "For businesses & firms" },
  { value: "Savings",           label: "Savings Account",         sub: "Individual / personal" },
  { value: "Cash Credit",       label: "Cash Credit (CC)",        sub: "Working capital facility" },
  { value: "Overdraft",         label: "Overdraft (OD)",          sub: "Credit against assets" },
  { value: "NRE",               label: "NRE Account",             sub: "Non-Resident External (INR)" },
  { value: "NRO",               label: "NRO Account",             sub: "Non-Resident Ordinary" },
  { value: "FCNR",              label: "FCNR Account",            sub: "Foreign Currency Non-Resident" },
  { value: "Fixed Deposit",     label: "Fixed Deposit (FD)",      sub: "Term deposit" },
  { value: "Recurring Deposit", label: "Recurring Deposit (RD)",  sub: "Monthly instalment deposit" },
];

// ── Indian States & Union Territories ────────────────────────────────────────
export const INDIAN_STATES: SelectOption[] = [
  // 28 States
  { value: "Andhra Pradesh",     label: "Andhra Pradesh",     sub: "State" },
  { value: "Arunachal Pradesh",  label: "Arunachal Pradesh",  sub: "State" },
  { value: "Assam",              label: "Assam",              sub: "State" },
  { value: "Bihar",              label: "Bihar",              sub: "State" },
  { value: "Chhattisgarh",       label: "Chhattisgarh",       sub: "State" },
  { value: "Goa",                label: "Goa",                sub: "State" },
  { value: "Gujarat",            label: "Gujarat",            sub: "State" },
  { value: "Haryana",            label: "Haryana",            sub: "State" },
  { value: "Himachal Pradesh",   label: "Himachal Pradesh",   sub: "State" },
  { value: "Jharkhand",          label: "Jharkhand",          sub: "State" },
  { value: "Karnataka",          label: "Karnataka",          sub: "State" },
  { value: "Kerala",             label: "Kerala",             sub: "State" },
  { value: "Madhya Pradesh",     label: "Madhya Pradesh",     sub: "State" },
  { value: "Maharashtra",        label: "Maharashtra",        sub: "State" },
  { value: "Manipur",            label: "Manipur",            sub: "State" },
  { value: "Meghalaya",          label: "Meghalaya",          sub: "State" },
  { value: "Mizoram",            label: "Mizoram",            sub: "State" },
  { value: "Nagaland",           label: "Nagaland",           sub: "State" },
  { value: "Odisha",             label: "Odisha",             sub: "State" },
  { value: "Punjab",             label: "Punjab",             sub: "State" },
  { value: "Rajasthan",          label: "Rajasthan",          sub: "State" },
  { value: "Sikkim",             label: "Sikkim",             sub: "State" },
  { value: "Tamil Nadu",         label: "Tamil Nadu",         sub: "State" },
  { value: "Telangana",          label: "Telangana",          sub: "State" },
  { value: "Tripura",            label: "Tripura",            sub: "State" },
  { value: "Uttar Pradesh",      label: "Uttar Pradesh",      sub: "State" },
  { value: "Uttarakhand",        label: "Uttarakhand",        sub: "State" },
  { value: "West Bengal",        label: "West Bengal",        sub: "State" },
  // 8 Union Territories
  { value: "Andaman and Nicobar Islands",                  label: "Andaman and Nicobar Islands",                  sub: "UT" },
  { value: "Chandigarh",                                   label: "Chandigarh",                                   sub: "UT" },
  { value: "Dadra and Nagar Haveli and Daman and Diu",     label: "Dadra and Nagar Haveli and Daman and Diu",     sub: "UT" },
  { value: "Delhi",                                        label: "Delhi (NCT)",                                  sub: "UT" },
  { value: "Jammu and Kashmir",                            label: "Jammu and Kashmir",                            sub: "UT" },
  { value: "Ladakh",                                       label: "Ladakh",                                       sub: "UT" },
  { value: "Lakshadweep",                                  label: "Lakshadweep",                                  sub: "UT" },
  { value: "Puducherry",                                   label: "Puducherry",                                   sub: "UT" },
];

// ── Major Indian Cities ───────────────────────────────────────────────────────
export const INDIAN_CITIES: SelectOption[] = [
  { value: "Mumbai",              label: "Mumbai",              sub: "Maharashtra" },
  { value: "Delhi",               label: "Delhi",               sub: "Delhi NCT" },
  { value: "Bengaluru",           label: "Bengaluru",           sub: "Karnataka" },
  { value: "Hyderabad",           label: "Hyderabad",           sub: "Telangana" },
  { value: "Ahmedabad",           label: "Ahmedabad",           sub: "Gujarat" },
  { value: "Chennai",             label: "Chennai",             sub: "Tamil Nadu" },
  { value: "Kolkata",             label: "Kolkata",             sub: "West Bengal" },
  { value: "Surat",               label: "Surat",               sub: "Gujarat" },
  { value: "Pune",                label: "Pune",                sub: "Maharashtra" },
  { value: "Jaipur",              label: "Jaipur",              sub: "Rajasthan" },
  { value: "Lucknow",             label: "Lucknow",             sub: "Uttar Pradesh" },
  { value: "Kanpur",              label: "Kanpur",              sub: "Uttar Pradesh" },
  { value: "Nagpur",              label: "Nagpur",              sub: "Maharashtra" },
  { value: "Indore",              label: "Indore",              sub: "Madhya Pradesh" },
  { value: "Thane",               label: "Thane",               sub: "Maharashtra" },
  { value: "Bhopal",              label: "Bhopal",              sub: "Madhya Pradesh" },
  { value: "Visakhapatnam",       label: "Visakhapatnam",       sub: "Andhra Pradesh" },
  { value: "Patna",               label: "Patna",               sub: "Bihar" },
  { value: "Vadodara",            label: "Vadodara",            sub: "Gujarat" },
  { value: "Ghaziabad",           label: "Ghaziabad",           sub: "Uttar Pradesh" },
  { value: "Ludhiana",            label: "Ludhiana",            sub: "Punjab" },
  { value: "Agra",                label: "Agra",                sub: "Uttar Pradesh" },
  { value: "Nashik",              label: "Nashik",              sub: "Maharashtra" },
  { value: "Faridabad",           label: "Faridabad",           sub: "Haryana" },
  { value: "Meerut",              label: "Meerut",              sub: "Uttar Pradesh" },
  { value: "Rajkot",              label: "Rajkot",              sub: "Gujarat" },
  { value: "Varanasi",            label: "Varanasi",            sub: "Uttar Pradesh" },
  { value: "Srinagar",            label: "Srinagar",            sub: "J&K" },
  { value: "Aurangabad",          label: "Aurangabad",          sub: "Maharashtra" },
  { value: "Dhanbad",             label: "Dhanbad",             sub: "Jharkhand" },
  { value: "Amritsar",            label: "Amritsar",            sub: "Punjab" },
  { value: "Navi Mumbai",         label: "Navi Mumbai",         sub: "Maharashtra" },
  { value: "Prayagraj",           label: "Prayagraj",           sub: "Uttar Pradesh" },
  { value: "Ranchi",              label: "Ranchi",              sub: "Jharkhand" },
  { value: "Howrah",              label: "Howrah",              sub: "West Bengal" },
  { value: "Coimbatore",          label: "Coimbatore",          sub: "Tamil Nadu" },
  { value: "Jabalpur",            label: "Jabalpur",            sub: "Madhya Pradesh" },
  { value: "Gwalior",             label: "Gwalior",             sub: "Madhya Pradesh" },
  { value: "Vijayawada",          label: "Vijayawada",          sub: "Andhra Pradesh" },
  { value: "Jodhpur",             label: "Jodhpur",             sub: "Rajasthan" },
  { value: "Madurai",             label: "Madurai",             sub: "Tamil Nadu" },
  { value: "Raipur",              label: "Raipur",              sub: "Chhattisgarh" },
  { value: "Kota",                label: "Kota",                sub: "Rajasthan" },
  { value: "Guwahati",            label: "Guwahati",            sub: "Assam" },
  { value: "Chandigarh",          label: "Chandigarh",          sub: "UT" },
  { value: "Solapur",             label: "Solapur",             sub: "Maharashtra" },
  { value: "Hubli-Dharwad",       label: "Hubli-Dharwad",       sub: "Karnataka" },
  { value: "Mysuru",              label: "Mysuru",              sub: "Karnataka" },
  { value: "Tiruchirappalli",     label: "Tiruchirappalli",     sub: "Tamil Nadu" },
  { value: "Bareilly",            label: "Bareilly",            sub: "Uttar Pradesh" },
  { value: "Aligarh",             label: "Aligarh",             sub: "Uttar Pradesh" },
  { value: "Tiruppur",            label: "Tiruppur",            sub: "Tamil Nadu" },
  { value: "Moradabad",           label: "Moradabad",           sub: "Uttar Pradesh" },
  { value: "Jalandhar",           label: "Jalandhar",           sub: "Punjab" },
  { value: "Bhubaneswar",         label: "Bhubaneswar",         sub: "Odisha" },
  { value: "Salem",               label: "Salem",               sub: "Tamil Nadu" },
  { value: "Warangal",            label: "Warangal",            sub: "Telangana" },
  { value: "Guntur",              label: "Guntur",              sub: "Andhra Pradesh" },
  { value: "Kochi",               label: "Kochi",               sub: "Kerala" },
  { value: "Thiruvananthapuram",  label: "Thiruvananthapuram",  sub: "Kerala" },
  { value: "Kozhikode",           label: "Kozhikode",           sub: "Kerala" },
  { value: "Mangaluru",           label: "Mangaluru",           sub: "Karnataka" },
  { value: "Udaipur",             label: "Udaipur",             sub: "Rajasthan" },
  { value: "Tirunelveli",         label: "Tirunelveli",         sub: "Tamil Nadu" },
  { value: "Jamshedpur",          label: "Jamshedpur",          sub: "Jharkhand" },
  { value: "Belagavi",            label: "Belagavi",            sub: "Karnataka" },
  { value: "Noida",               label: "Noida",               sub: "Uttar Pradesh" },
  { value: "Gurugram",            label: "Gurugram",            sub: "Haryana" },
  { value: "Dehradun",            label: "Dehradun",            sub: "Uttarakhand" },
  { value: "Shimla",              label: "Shimla",              sub: "Himachal Pradesh" },
  { value: "Jammu",               label: "Jammu",               sub: "J&K" },
  { value: "Puducherry",          label: "Puducherry",          sub: "UT" },
  { value: "Panaji",              label: "Panaji",              sub: "Goa" },
  { value: "Imphal",              label: "Imphal",              sub: "Manipur" },
  { value: "Shillong",            label: "Shillong",            sub: "Meghalaya" },
  { value: "Agartala",            label: "Agartala",            sub: "Tripura" },
  { value: "Itanagar",            label: "Itanagar",            sub: "Arunachal Pradesh" },
  { value: "Dispur",              label: "Dispur",              sub: "Assam" },
  { value: "Gangtok",             label: "Gangtok",             sub: "Sikkim" },
  { value: "Kohima",              label: "Kohima",              sub: "Nagaland" },
  { value: "Aizawl",              label: "Aizawl",              sub: "Mizoram" },
];

// ── Countries (India first, then alphabetical) ────────────────────────────────
export const COUNTRIES: SelectOption[] = [
  { value: "India",                label: "🇮🇳 India",                sub: "Default" },
  { value: "Afghanistan",          label: "Afghanistan" },
  { value: "Australia",            label: "🇦🇺 Australia" },
  { value: "Bahrain",              label: "🇧🇭 Bahrain" },
  { value: "Bangladesh",           label: "🇧🇩 Bangladesh" },
  { value: "Belgium",              label: "🇧🇪 Belgium" },
  { value: "Brazil",               label: "🇧🇷 Brazil" },
  { value: "Canada",               label: "🇨🇦 Canada" },
  { value: "China",                label: "🇨🇳 China" },
  { value: "Denmark",              label: "🇩🇰 Denmark" },
  { value: "Egypt",                label: "🇪🇬 Egypt" },
  { value: "Ethiopia",             label: "Ethiopia" },
  { value: "Finland",              label: "Finland" },
  { value: "France",               label: "🇫🇷 France" },
  { value: "Germany",              label: "🇩🇪 Germany" },
  { value: "Ghana",                label: "Ghana" },
  { value: "Hong Kong",            label: "🇭🇰 Hong Kong" },
  { value: "Indonesia",            label: "🇮🇩 Indonesia" },
  { value: "Iran",                 label: "Iran" },
  { value: "Iraq",                 label: "Iraq" },
  { value: "Ireland",              label: "🇮🇪 Ireland" },
  { value: "Israel",               label: "🇮🇱 Israel" },
  { value: "Italy",                label: "🇮🇹 Italy" },
  { value: "Japan",                label: "🇯🇵 Japan" },
  { value: "Jordan",               label: "Jordan" },
  { value: "Kenya",                label: "Kenya" },
  { value: "Kuwait",               label: "🇰🇼 Kuwait" },
  { value: "Malaysia",             label: "🇲🇾 Malaysia" },
  { value: "Maldives",             label: "Maldives" },
  { value: "Mauritius",            label: "Mauritius" },
  { value: "Mexico",               label: "🇲🇽 Mexico" },
  { value: "Myanmar",              label: "Myanmar" },
  { value: "Nepal",                label: "🇳🇵 Nepal" },
  { value: "Netherlands",          label: "🇳🇱 Netherlands" },
  { value: "New Zealand",          label: "🇳🇿 New Zealand" },
  { value: "Nigeria",              label: "Nigeria" },
  { value: "Norway",               label: "Norway" },
  { value: "Oman",                 label: "🇴🇲 Oman" },
  { value: "Pakistan",             label: "🇵🇰 Pakistan" },
  { value: "Philippines",          label: "🇵🇭 Philippines" },
  { value: "Portugal",             label: "Portugal" },
  { value: "Qatar",                label: "🇶🇦 Qatar" },
  { value: "Russia",               label: "🇷🇺 Russia" },
  { value: "Saudi Arabia",         label: "🇸🇦 Saudi Arabia" },
  { value: "Singapore",            label: "🇸🇬 Singapore" },
  { value: "South Africa",         label: "🇿🇦 South Africa" },
  { value: "South Korea",          label: "🇰🇷 South Korea" },
  { value: "Spain",                label: "🇪🇸 Spain" },
  { value: "Sri Lanka",            label: "🇱🇰 Sri Lanka" },
  { value: "Sweden",               label: "Sweden" },
  { value: "Switzerland",          label: "🇨🇭 Switzerland" },
  { value: "Taiwan",               label: "Taiwan" },
  { value: "Tanzania",             label: "Tanzania" },
  { value: "Thailand",             label: "🇹🇭 Thailand" },
  { value: "Turkey",               label: "🇹🇷 Turkey" },
  { value: "Uganda",               label: "Uganda" },
  { value: "Ukraine",              label: "Ukraine" },
  { value: "United Arab Emirates", label: "🇦🇪 United Arab Emirates" },
  { value: "United Kingdom",       label: "🇬🇧 United Kingdom" },
  { value: "United States",        label: "🇺🇸 United States" },
  { value: "Vietnam",              label: "🇻🇳 Vietnam" },
  { value: "Zambia",               label: "Zambia" },
  { value: "Zimbabwe",             label: "Zimbabwe" },
];

// ── India: cities grouped by state ───────────────────────────────────────────
export const INDIA_STATE_CITIES_MAP: Record<string, SelectOption[]> = {
  "Andhra Pradesh":    [{ value:"Visakhapatnam",label:"Visakhapatnam"},{value:"Vijayawada",label:"Vijayawada"},{value:"Guntur",label:"Guntur"},{value:"Tirupati",label:"Tirupati"},{value:"Kurnool",label:"Kurnool"},{value:"Nellore",label:"Nellore"}],
  "Arunachal Pradesh": [{ value:"Itanagar",label:"Itanagar"},{value:"Naharlagun",label:"Naharlagun"}],
  "Assam":             [{ value:"Guwahati",label:"Guwahati"},{value:"Dispur",label:"Dispur (Capital)"},{value:"Silchar",label:"Silchar"},{value:"Dibrugarh",label:"Dibrugarh"}],
  "Bihar":             [{ value:"Patna",label:"Patna"},{value:"Gaya",label:"Gaya"},{value:"Muzaffarpur",label:"Muzaffarpur"},{value:"Bhagalpur",label:"Bhagalpur"},{value:"Darbhanga",label:"Darbhanga"}],
  "Chhattisgarh":      [{ value:"Raipur",label:"Raipur"},{value:"Bhilai",label:"Bhilai"},{value:"Bilaspur",label:"Bilaspur"},{value:"Korba",label:"Korba"}],
  "Goa":               [{ value:"Panaji",label:"Panaji (Capital)"},{value:"Margao",label:"Margao"},{value:"Vasco da Gama",label:"Vasco da Gama"},{value:"Mapusa",label:"Mapusa"}],
  "Gujarat":           [{ value:"Ahmedabad",label:"Ahmedabad"},{value:"Surat",label:"Surat"},{value:"Vadodara",label:"Vadodara"},{value:"Rajkot",label:"Rajkot"},{value:"Bhavnagar",label:"Bhavnagar"},{value:"Jamnagar",label:"Jamnagar"},{value:"Gandhinagar",label:"Gandhinagar (Capital)"},{value:"Anand",label:"Anand"}],
  "Haryana":           [{ value:"Gurugram",label:"Gurugram"},{value:"Faridabad",label:"Faridabad"},{value:"Panipat",label:"Panipat"},{value:"Ambala",label:"Ambala"},{value:"Sonipat",label:"Sonipat"},{value:"Rohtak",label:"Rohtak"},{value:"Chandigarh",label:"Chandigarh (shared)"},{value:"Hisar",label:"Hisar"}],
  "Himachal Pradesh":  [{ value:"Shimla",label:"Shimla (Capital)"},{value:"Dharamshala",label:"Dharamshala"},{value:"Solan",label:"Solan"},{value:"Mandi",label:"Mandi"},{value:"Baddi",label:"Baddi"}],
  "Jharkhand":         [{ value:"Ranchi",label:"Ranchi (Capital)"},{value:"Dhanbad",label:"Dhanbad"},{value:"Jamshedpur",label:"Jamshedpur"},{value:"Bokaro",label:"Bokaro Steel City"}],
  "Karnataka":         [{ value:"Bengaluru",label:"Bengaluru"},{value:"Mysuru",label:"Mysuru"},{value:"Hubli-Dharwad",label:"Hubli-Dharwad"},{value:"Mangaluru",label:"Mangaluru"},{value:"Belagavi",label:"Belagavi"},{value:"Tumakuru",label:"Tumakuru"},{value:"Shivamogga",label:"Shivamogga"},{value:"Kalaburagi",label:"Kalaburagi"}],
  "Kerala":            [{ value:"Kochi",label:"Kochi"},{value:"Thiruvananthapuram",label:"Thiruvananthapuram (Capital)"},{value:"Kozhikode",label:"Kozhikode"},{value:"Thrissur",label:"Thrissur"},{value:"Kollam",label:"Kollam"},{value:"Palakkad",label:"Palakkad"},{value:"Kannur",label:"Kannur"}],
  "Madhya Pradesh":    [{ value:"Indore",label:"Indore"},{value:"Bhopal",label:"Bhopal (Capital)"},{value:"Jabalpur",label:"Jabalpur"},{value:"Gwalior",label:"Gwalior"},{value:"Ujjain",label:"Ujjain"},{value:"Rewa",label:"Rewa"},{value:"Sagar",label:"Sagar"}],
  "Maharashtra":       [{ value:"Mumbai",label:"Mumbai"},{value:"Pune",label:"Pune"},{value:"Nagpur",label:"Nagpur"},{value:"Thane",label:"Thane"},{value:"Navi Mumbai",label:"Navi Mumbai"},{value:"Nashik",label:"Nashik"},{value:"Aurangabad",label:"Aurangabad (Chhatrapati Sambhajinagar)"},{value:"Solapur",label:"Solapur"},{value:"Kolhapur",label:"Kolhapur"},{value:"Amravati",label:"Amravati"}],
  "Manipur":           [{ value:"Imphal",label:"Imphal (Capital)"},{value:"Thoubal",label:"Thoubal"},{value:"Bishnupur",label:"Bishnupur"}],
  "Meghalaya":         [{ value:"Shillong",label:"Shillong (Capital)"},{value:"Tura",label:"Tura"}],
  "Mizoram":           [{ value:"Aizawl",label:"Aizawl (Capital)"},{value:"Lunglei",label:"Lunglei"}],
  "Nagaland":          [{ value:"Kohima",label:"Kohima (Capital)"},{value:"Dimapur",label:"Dimapur"}],
  "Odisha":            [{ value:"Bhubaneswar",label:"Bhubaneswar (Capital)"},{value:"Cuttack",label:"Cuttack"},{value:"Rourkela",label:"Rourkela"},{value:"Sambalpur",label:"Sambalpur"},{value:"Puri",label:"Puri"}],
  "Punjab":            [{ value:"Ludhiana",label:"Ludhiana"},{value:"Amritsar",label:"Amritsar"},{value:"Jalandhar",label:"Jalandhar"},{value:"Patiala",label:"Patiala"},{value:"Bathinda",label:"Bathinda"},{value:"Chandigarh",label:"Chandigarh (shared)"},{value:"Mohali",label:"Mohali (SAS Nagar)"}],
  "Rajasthan":         [{ value:"Jaipur",label:"Jaipur (Capital)"},{value:"Jodhpur",label:"Jodhpur"},{value:"Kota",label:"Kota"},{value:"Udaipur",label:"Udaipur"},{value:"Bikaner",label:"Bikaner"},{value:"Ajmer",label:"Ajmer"},{value:"Alwar",label:"Alwar"}],
  "Sikkim":            [{ value:"Gangtok",label:"Gangtok (Capital)"},{value:"Namchi",label:"Namchi"}],
  "Tamil Nadu":        [{ value:"Chennai",label:"Chennai (Capital)"},{value:"Coimbatore",label:"Coimbatore"},{value:"Madurai",label:"Madurai"},{value:"Tiruppur",label:"Tiruppur"},{value:"Salem",label:"Salem"},{value:"Tiruchirappalli",label:"Tiruchirappalli"},{value:"Tirunelveli",label:"Tirunelveli"},{value:"Erode",label:"Erode"},{value:"Vellore",label:"Vellore"},{value:"Thoothukudi",label:"Thoothukudi"}],
  "Telangana":         [{ value:"Hyderabad",label:"Hyderabad (Capital)"},{value:"Warangal",label:"Warangal"},{value:"Nizamabad",label:"Nizamabad"},{value:"Khammam",label:"Khammam"},{value:"Karimnagar",label:"Karimnagar"}],
  "Tripura":           [{ value:"Agartala",label:"Agartala (Capital)"},{value:"Udaipur",label:"Udaipur (Tripura)"}],
  "Uttar Pradesh":     [{ value:"Lucknow",label:"Lucknow (Capital)"},{value:"Kanpur",label:"Kanpur"},{value:"Ghaziabad",label:"Ghaziabad"},{value:"Agra",label:"Agra"},{value:"Meerut",label:"Meerut"},{value:"Varanasi",label:"Varanasi"},{value:"Noida",label:"Noida"},{value:"Prayagraj",label:"Prayagraj"},{value:"Bareilly",label:"Bareilly"},{value:"Aligarh",label:"Aligarh"},{value:"Moradabad",label:"Moradabad"},{value:"Firozabad",label:"Firozabad"},{value:"Saharanpur",label:"Saharanpur"},{value:"Mathura",label:"Mathura"},{value:"Gorakhpur",label:"Gorakhpur"}],
  "Uttarakhand":       [{ value:"Dehradun",label:"Dehradun (Capital)"},{value:"Haridwar",label:"Haridwar"},{value:"Rishikesh",label:"Rishikesh"},{value:"Roorkee",label:"Roorkee"},{value:"Haldwani",label:"Haldwani"}],
  "West Bengal":       [{ value:"Kolkata",label:"Kolkata (Capital)"},{value:"Howrah",label:"Howrah"},{value:"Durgapur",label:"Durgapur"},{value:"Siliguri",label:"Siliguri"},{value:"Asansol",label:"Asansol"},{value:"Bardhaman",label:"Bardhaman"}],
  // Union Territories
  "Delhi":                                       [{ value:"New Delhi",label:"New Delhi (Capital Territory)"},{value:"Dwarka",label:"Dwarka"},{value:"Rohini",label:"Rohini"},{value:"Pitampura",label:"Pitampura"},{value:"Saket",label:"Saket"},{value:"Lajpat Nagar",label:"Lajpat Nagar"},{value:"Connaught Place",label:"Connaught Place"}],
  "Jammu and Kashmir":                           [{ value:"Srinagar",label:"Srinagar (Summer Capital)"},{value:"Jammu",label:"Jammu (Winter Capital)"},{value:"Anantnag",label:"Anantnag"},{value:"Sopore",label:"Sopore"}],
  "Ladakh":                                      [{ value:"Leh",label:"Leh (HQ)"},{value:"Kargil",label:"Kargil"}],
  "Chandigarh":                                  [{ value:"Chandigarh",label:"Chandigarh"}],
  "Puducherry":                                  [{ value:"Puducherry",label:"Puducherry (Capital)"},{value:"Karaikal",label:"Karaikal"},{value:"Mahe",label:"Mahe"},{value:"Yanam",label:"Yanam"}],
  "Andaman and Nicobar Islands":                 [{ value:"Port Blair",label:"Port Blair (Capital)"}],
  "Dadra and Nagar Haveli and Daman and Diu":    [{ value:"Daman",label:"Daman"},{value:"Diu",label:"Diu"},{value:"Silvassa",label:"Silvassa"}],
  "Lakshadweep":                                 [{ value:"Kavaratti",label:"Kavaratti (Capital)"},{value:"Agatti",label:"Agatti"}],
};

// ── International: cities grouped by country → state/province ────────────────
export const INTL_STATE_CITIES_MAP: Record<string, Record<string, SelectOption[]>> = {
  "United States": {
    "California":      [{ value:"Los Angeles",label:"Los Angeles"},{value:"San Francisco",label:"San Francisco"},{value:"San Diego",label:"San Diego"},{value:"San Jose",label:"San Jose"},{value:"Sacramento",label:"Sacramento"},{value:"Oakland",label:"Oakland"},{value:"Fresno",label:"Fresno"},{value:"Long Beach",label:"Long Beach"}],
    "Texas":           [{ value:"Houston",label:"Houston"},{value:"Dallas",label:"Dallas"},{value:"Austin",label:"Austin"},{value:"San Antonio",label:"San Antonio"},{value:"Fort Worth",label:"Fort Worth"},{value:"El Paso",label:"El Paso"},{value:"Arlington",label:"Arlington"},{value:"Plano",label:"Plano"}],
    "New York":        [{ value:"New York City",label:"New York City"},{value:"Buffalo",label:"Buffalo"},{value:"Rochester",label:"Rochester"},{value:"Yonkers",label:"Yonkers"},{value:"Syracuse",label:"Syracuse"},{value:"Albany",label:"Albany"}],
    "Florida":         [{ value:"Miami",label:"Miami"},{value:"Tampa",label:"Tampa"},{value:"Orlando",label:"Orlando"},{value:"Jacksonville",label:"Jacksonville"},{value:"Fort Lauderdale",label:"Fort Lauderdale"},{value:"St. Petersburg",label:"St. Petersburg"}],
    "Illinois":        [{ value:"Chicago",label:"Chicago"},{value:"Aurora",label:"Aurora"},{value:"Naperville",label:"Naperville"},{value:"Joliet",label:"Joliet"},{value:"Rockford",label:"Rockford"}],
    "Pennsylvania":    [{ value:"Philadelphia",label:"Philadelphia"},{value:"Pittsburgh",label:"Pittsburgh"},{value:"Allentown",label:"Allentown"},{value:"Erie",label:"Erie"}],
    "Ohio":            [{ value:"Columbus",label:"Columbus"},{value:"Cleveland",label:"Cleveland"},{value:"Cincinnati",label:"Cincinnati"},{value:"Toledo",label:"Toledo"},{value:"Akron",label:"Akron"}],
    "Georgia":         [{ value:"Atlanta",label:"Atlanta"},{value:"Augusta",label:"Augusta"},{value:"Savannah",label:"Savannah"},{value:"Columbus",label:"Columbus"}],
    "North Carolina":  [{ value:"Charlotte",label:"Charlotte"},{value:"Raleigh",label:"Raleigh"},{value:"Greensboro",label:"Greensboro"},{value:"Durham",label:"Durham"}],
    "Michigan":        [{ value:"Detroit",label:"Detroit"},{value:"Grand Rapids",label:"Grand Rapids"},{value:"Lansing",label:"Lansing"},{value:"Ann Arbor",label:"Ann Arbor"}],
    "Washington":      [{ value:"Seattle",label:"Seattle"},{value:"Spokane",label:"Spokane"},{value:"Tacoma",label:"Tacoma"},{value:"Bellevue",label:"Bellevue"}],
    "Massachusetts":   [{ value:"Boston",label:"Boston"},{value:"Worcester",label:"Worcester"},{value:"Springfield",label:"Springfield"},{value:"Cambridge",label:"Cambridge"}],
    "Arizona":         [{ value:"Phoenix",label:"Phoenix"},{value:"Tucson",label:"Tucson"},{value:"Scottsdale",label:"Scottsdale"},{value:"Mesa",label:"Mesa"}],
    "Colorado":        [{ value:"Denver",label:"Denver"},{value:"Colorado Springs",label:"Colorado Springs"},{value:"Aurora",label:"Aurora"},{value:"Boulder",label:"Boulder"}],
    "Nevada":          [{ value:"Las Vegas",label:"Las Vegas"},{value:"Henderson",label:"Henderson"},{value:"Reno",label:"Reno"},{value:"North Las Vegas",label:"North Las Vegas"}],
    "Minnesota":       [{ value:"Minneapolis",label:"Minneapolis"},{value:"Saint Paul",label:"Saint Paul"},{value:"Rochester",label:"Rochester"}],
    "Missouri":        [{ value:"Kansas City",label:"Kansas City"},{value:"St. Louis",label:"St. Louis"},{value:"Springfield",label:"Springfield"}],
    "Tennessee":       [{ value:"Nashville",label:"Nashville"},{value:"Memphis",label:"Memphis"},{value:"Knoxville",label:"Knoxville"},{value:"Chattanooga",label:"Chattanooga"}],
    "Indiana":         [{ value:"Indianapolis",label:"Indianapolis"},{value:"Fort Wayne",label:"Fort Wayne"},{value:"Evansville",label:"Evansville"}],
    "Wisconsin":       [{ value:"Milwaukee",label:"Milwaukee"},{value:"Madison",label:"Madison"},{value:"Green Bay",label:"Green Bay"}],
    "Maryland":        [{ value:"Baltimore",label:"Baltimore"},{value:"Rockville",label:"Rockville"},{value:"Gaithersburg",label:"Gaithersburg"}],
    "Virginia":        [{ value:"Virginia Beach",label:"Virginia Beach"},{value:"Norfolk",label:"Norfolk"},{value:"Chesapeake",label:"Chesapeake"},{value:"Richmond",label:"Richmond"}],
    "Oregon":          [{ value:"Portland",label:"Portland"},{value:"Salem",label:"Salem"},{value:"Eugene",label:"Eugene"}],
    "New Jersey":      [{ value:"Newark",label:"Newark"},{value:"Jersey City",label:"Jersey City"},{value:"Paterson",label:"Paterson"},{value:"Trenton",label:"Trenton"}],
    "District of Columbia": [{ value:"Washington D.C.",label:"Washington D.C."}],
  },
  "United Kingdom": {
    "England":          [{ value:"London",label:"London"},{value:"Manchester",label:"Manchester"},{value:"Birmingham",label:"Birmingham"},{value:"Leeds",label:"Leeds"},{value:"Liverpool",label:"Liverpool"},{value:"Sheffield",label:"Sheffield"},{value:"Bristol",label:"Bristol"},{value:"Newcastle",label:"Newcastle upon Tyne"},{value:"Nottingham",label:"Nottingham"},{value:"Leicester",label:"Leicester"},{value:"Coventry",label:"Coventry"},{value:"Bradford",label:"Bradford"},{value:"Oxford",label:"Oxford"},{value:"Cambridge",label:"Cambridge"},{value:"Southampton",label:"Southampton"},{value:"Portsmouth",label:"Portsmouth"}],
    "Scotland":         [{ value:"Edinburgh",label:"Edinburgh"},{value:"Glasgow",label:"Glasgow"},{value:"Aberdeen",label:"Aberdeen"},{value:"Dundee",label:"Dundee"},{value:"Inverness",label:"Inverness"},{value:"Stirling",label:"Stirling"}],
    "Wales":            [{ value:"Cardiff",label:"Cardiff"},{value:"Swansea",label:"Swansea"},{value:"Newport",label:"Newport"},{value:"Wrexham",label:"Wrexham"}],
    "Northern Ireland": [{ value:"Belfast",label:"Belfast"},{value:"Derry",label:"Derry / Londonderry"},{value:"Lisburn",label:"Lisburn"},{value:"Newry",label:"Newry"}],
  },
  "United Arab Emirates": {
    "Dubai":          [{ value:"Downtown Dubai",label:"Downtown Dubai"},{value:"Deira",label:"Deira"},{value:"Bur Dubai",label:"Bur Dubai"},{value:"Jumeirah",label:"Jumeirah"},{value:"Dubai Marina",label:"Dubai Marina"},{value:"Business Bay",label:"Business Bay"},{value:"JBR",label:"Jumeirah Beach Residence"},{value:"Al Quoz",label:"Al Quoz"},{value:"DIFC",label:"DIFC"},{value:"Dubai Silicon Oasis",label:"Dubai Silicon Oasis"}],
    "Abu Dhabi":      [{ value:"Abu Dhabi City",label:"Abu Dhabi City"},{value:"Al Ain",label:"Al Ain"},{value:"Khalifa City",label:"Khalifa City"},{value:"Mussafah",label:"Mussafah"}],
    "Sharjah":        [{ value:"Sharjah City",label:"Sharjah City"},{value:"Khor Fakkan",label:"Khor Fakkan"},{value:"Kalba",label:"Kalba"}],
    "Ajman":          [{ value:"Ajman City",label:"Ajman City"}],
    "Ras Al Khaimah": [{ value:"Ras Al Khaimah City",label:"Ras Al Khaimah City"},{value:"Al Hamra",label:"Al Hamra"}],
    "Fujairah":       [{ value:"Fujairah City",label:"Fujairah City"},{value:"Dibba Al Fujairah",label:"Dibba Al Fujairah"}],
    "Umm Al Quwain":  [{ value:"Umm Al Quwain City",label:"Umm Al Quwain City"}],
  },
  "Australia": {
    "New South Wales":    [{ value:"Sydney",label:"Sydney"},{value:"Newcastle",label:"Newcastle"},{value:"Wollongong",label:"Wollongong"},{value:"Central Coast",label:"Central Coast"},{value:"Maitland",label:"Maitland"},{value:"Albury",label:"Albury"},{value:"Orange",label:"Orange"}],
    "Victoria":           [{ value:"Melbourne",label:"Melbourne"},{value:"Geelong",label:"Geelong"},{value:"Ballarat",label:"Ballarat"},{value:"Bendigo",label:"Bendigo"},{value:"Frankston",label:"Frankston"}],
    "Queensland":         [{ value:"Brisbane",label:"Brisbane"},{value:"Gold Coast",label:"Gold Coast"},{value:"Sunshine Coast",label:"Sunshine Coast"},{value:"Townsville",label:"Townsville"},{value:"Cairns",label:"Cairns"},{value:"Toowoomba",label:"Toowoomba"}],
    "Western Australia":  [{ value:"Perth",label:"Perth"},{value:"Mandurah",label:"Mandurah"},{value:"Bunbury",label:"Bunbury"},{value:"Geraldton",label:"Geraldton"},{value:"Kalgoorlie",label:"Kalgoorlie"}],
    "South Australia":    [{ value:"Adelaide",label:"Adelaide"},{value:"Mount Gambier",label:"Mount Gambier"},{value:"Whyalla",label:"Whyalla"}],
    "Tasmania":           [{ value:"Hobart",label:"Hobart"},{value:"Launceston",label:"Launceston"},{value:"Devonport",label:"Devonport"}],
    "Australian Capital Territory": [{ value:"Canberra",label:"Canberra"}],
    "Northern Territory": [{ value:"Darwin",label:"Darwin"},{value:"Alice Springs",label:"Alice Springs"}],
  },
  "Canada": {
    "Ontario":                   [{ value:"Toronto",label:"Toronto"},{value:"Ottawa",label:"Ottawa"},{value:"Hamilton",label:"Hamilton"},{value:"London",label:"London"},{value:"Mississauga",label:"Mississauga"},{value:"Brampton",label:"Brampton"},{value:"Markham",label:"Markham"},{value:"Kitchener",label:"Kitchener"}],
    "Quebec":                    [{ value:"Montreal",label:"Montréal"},{value:"Quebec City",label:"Québec City"},{value:"Laval",label:"Laval"},{value:"Gatineau",label:"Gatineau"},{value:"Longueuil",label:"Longueuil"}],
    "British Columbia":          [{ value:"Vancouver",label:"Vancouver"},{value:"Surrey",label:"Surrey"},{value:"Burnaby",label:"Burnaby"},{value:"Richmond",label:"Richmond"},{value:"Victoria",label:"Victoria"},{value:"Kelowna",label:"Kelowna"}],
    "Alberta":                   [{ value:"Calgary",label:"Calgary"},{value:"Edmonton",label:"Edmonton"},{value:"Red Deer",label:"Red Deer"},{value:"Lethbridge",label:"Lethbridge"}],
    "Manitoba":                  [{ value:"Winnipeg",label:"Winnipeg"},{value:"Brandon",label:"Brandon"}],
    "Saskatchewan":              [{ value:"Saskatoon",label:"Saskatoon"},{value:"Regina",label:"Regina"}],
    "Nova Scotia":               [{ value:"Halifax",label:"Halifax"},{value:"Dartmouth",label:"Dartmouth"}],
    "New Brunswick":             [{ value:"Moncton",label:"Moncton"},{value:"Fredericton",label:"Fredericton"},{value:"Saint John",label:"Saint John"}],
    "Newfoundland and Labrador": [{ value:"St. John's",label:"St. John's"}],
    "Prince Edward Island":      [{ value:"Charlottetown",label:"Charlottetown"}],
    "Northwest Territories":     [{ value:"Yellowknife",label:"Yellowknife"}],
    "Yukon":                     [{ value:"Whitehorse",label:"Whitehorse"}],
    "Nunavut":                   [{ value:"Iqaluit",label:"Iqaluit"}],
  },
  "Saudi Arabia": {
    "Riyadh Region":    [{ value:"Riyadh",label:"Riyadh"},{value:"Al Kharj",label:"Al Kharj"},{value:"Zulfi",label:"Zulfi"}],
    "Makkah Region":    [{ value:"Mecca",label:"Mecca"},{value:"Jeddah",label:"Jeddah"},{value:"Taif",label:"Taif"}],
    "Madinah Region":   [{ value:"Medina",label:"Medina"},{value:"Yanbu",label:"Yanbu"}],
    "Eastern Province": [{ value:"Dammam",label:"Dammam"},{value:"Dhahran",label:"Dhahran"},{value:"Al Khobar",label:"Al Khobar"},{value:"Jubail",label:"Jubail"}],
    "Asir Region":      [{ value:"Abha",label:"Abha"},{value:"Khamis Mushait",label:"Khamis Mushait"}],
    "Tabuk Region":     [{ value:"Tabuk",label:"Tabuk"}],
    "Jizan Region":     [{ value:"Jizan",label:"Jizan"}],
    "Najran Region":    [{ value:"Najran",label:"Najran"}],
    "Al Bahah Region":  [{ value:"Al Bahah",label:"Al Bahah"}],
    "Al Jouf Region":   [{ value:"Sakaka",label:"Sakaka"}],
    "Ha'il Region":     [{ value:"Ha'il",label:"Ha'il"}],
    "Qassim Region":    [{ value:"Buraidah",label:"Buraidah"},{value:"Unaizah",label:"Unaizah"}],
    "Northern Borders": [{ value:"Arar",label:"Arar"}],
  },
};

// ── Country → States/Provinces ───────────────────────────────────────────────
export const COUNTRY_STATES_MAP: Record<string, SelectOption[]> = {
  "India": INDIAN_STATES,
  "United States": [
    { value:"Alabama",label:"Alabama",sub:"AL" },{ value:"Alaska",label:"Alaska",sub:"AK" },{ value:"Arizona",label:"Arizona",sub:"AZ" },{ value:"Arkansas",label:"Arkansas",sub:"AR" },{ value:"California",label:"California",sub:"CA" },{ value:"Colorado",label:"Colorado",sub:"CO" },{ value:"Connecticut",label:"Connecticut",sub:"CT" },{ value:"Delaware",label:"Delaware",sub:"DE" },{ value:"District of Columbia",label:"District of Columbia",sub:"DC" },{ value:"Florida",label:"Florida",sub:"FL" },{ value:"Georgia",label:"Georgia",sub:"GA" },{ value:"Hawaii",label:"Hawaii",sub:"HI" },{ value:"Idaho",label:"Idaho",sub:"ID" },{ value:"Illinois",label:"Illinois",sub:"IL" },{ value:"Indiana",label:"Indiana",sub:"IN" },{ value:"Iowa",label:"Iowa",sub:"IA" },{ value:"Kansas",label:"Kansas",sub:"KS" },{ value:"Kentucky",label:"Kentucky",sub:"KY" },{ value:"Louisiana",label:"Louisiana",sub:"LA" },{ value:"Maine",label:"Maine",sub:"ME" },{ value:"Maryland",label:"Maryland",sub:"MD" },{ value:"Massachusetts",label:"Massachusetts",sub:"MA" },{ value:"Michigan",label:"Michigan",sub:"MI" },{ value:"Minnesota",label:"Minnesota",sub:"MN" },{ value:"Mississippi",label:"Mississippi",sub:"MS" },{ value:"Missouri",label:"Missouri",sub:"MO" },{ value:"Montana",label:"Montana",sub:"MT" },{ value:"Nebraska",label:"Nebraska",sub:"NE" },{ value:"Nevada",label:"Nevada",sub:"NV" },{ value:"New Hampshire",label:"New Hampshire",sub:"NH" },{ value:"New Jersey",label:"New Jersey",sub:"NJ" },{ value:"New Mexico",label:"New Mexico",sub:"NM" },{ value:"New York",label:"New York",sub:"NY" },{ value:"North Carolina",label:"North Carolina",sub:"NC" },{ value:"North Dakota",label:"North Dakota",sub:"ND" },{ value:"Ohio",label:"Ohio",sub:"OH" },{ value:"Oklahoma",label:"Oklahoma",sub:"OK" },{ value:"Oregon",label:"Oregon",sub:"OR" },{ value:"Pennsylvania",label:"Pennsylvania",sub:"PA" },{ value:"Rhode Island",label:"Rhode Island",sub:"RI" },{ value:"South Carolina",label:"South Carolina",sub:"SC" },{ value:"South Dakota",label:"South Dakota",sub:"SD" },{ value:"Tennessee",label:"Tennessee",sub:"TN" },{ value:"Texas",label:"Texas",sub:"TX" },{ value:"Utah",label:"Utah",sub:"UT" },{ value:"Vermont",label:"Vermont",sub:"VT" },{ value:"Virginia",label:"Virginia",sub:"VA" },{ value:"Washington",label:"Washington",sub:"WA" },{ value:"West Virginia",label:"West Virginia",sub:"WV" },{ value:"Wisconsin",label:"Wisconsin",sub:"WI" },{ value:"Wyoming",label:"Wyoming",sub:"WY" },
  ],
  "United Kingdom": [
    { value:"England",label:"England" },{ value:"Scotland",label:"Scotland" },{ value:"Wales",label:"Wales" },{ value:"Northern Ireland",label:"Northern Ireland" },
  ],
  "Australia": [
    { value:"New South Wales",label:"New South Wales",sub:"NSW" },{ value:"Victoria",label:"Victoria",sub:"VIC" },{ value:"Queensland",label:"Queensland",sub:"QLD" },{ value:"Western Australia",label:"Western Australia",sub:"WA" },{ value:"South Australia",label:"South Australia",sub:"SA" },{ value:"Tasmania",label:"Tasmania",sub:"TAS" },{ value:"Australian Capital Territory",label:"Australian Capital Territory",sub:"ACT" },{ value:"Northern Territory",label:"Northern Territory",sub:"NT" },
  ],
  "Canada": [
    { value:"Ontario",label:"Ontario" },{ value:"Quebec",label:"Québec" },{ value:"British Columbia",label:"British Columbia" },{ value:"Alberta",label:"Alberta" },{ value:"Manitoba",label:"Manitoba" },{ value:"Saskatchewan",label:"Saskatchewan" },{ value:"Nova Scotia",label:"Nova Scotia" },{ value:"New Brunswick",label:"New Brunswick" },{ value:"Newfoundland and Labrador",label:"Newfoundland and Labrador" },{ value:"Prince Edward Island",label:"Prince Edward Island" },{ value:"Northwest Territories",label:"Northwest Territories" },{ value:"Yukon",label:"Yukon" },{ value:"Nunavut",label:"Nunavut" },
  ],
  "United Arab Emirates": [
    { value:"Abu Dhabi",label:"Abu Dhabi" },{ value:"Dubai",label:"Dubai" },{ value:"Sharjah",label:"Sharjah" },{ value:"Ajman",label:"Ajman" },{ value:"Umm Al Quwain",label:"Umm Al Quwain" },{ value:"Ras Al Khaimah",label:"Ras Al Khaimah" },{ value:"Fujairah",label:"Fujairah" },
  ],
  "Saudi Arabia": [
    { value:"Riyadh Region",label:"Riyadh Region" },{ value:"Makkah Region",label:"Makkah Region" },{ value:"Madinah Region",label:"Madinah Region" },{ value:"Qassim Region",label:"Qassim Region" },{ value:"Eastern Province",label:"Eastern Province" },{ value:"Asir Region",label:"Asir Region" },{ value:"Tabuk Region",label:"Tabuk Region" },{ value:"Ha'il Region",label:"Ha'il Region" },{ value:"Northern Borders",label:"Northern Borders" },{ value:"Jizan Region",label:"Jizan Region" },{ value:"Najran Region",label:"Najran Region" },{ value:"Al Bahah Region",label:"Al Bahah Region" },{ value:"Al Jouf Region",label:"Al Jouf Region" },
  ],
  "Germany": [
    { value:"Baden-Württemberg",label:"Baden-Württemberg" },{ value:"Bavaria",label:"Bavaria" },{ value:"Berlin",label:"Berlin" },{ value:"Brandenburg",label:"Brandenburg" },{ value:"Bremen",label:"Bremen" },{ value:"Hamburg",label:"Hamburg" },{ value:"Hesse",label:"Hesse" },{ value:"Lower Saxony",label:"Lower Saxony" },{ value:"Mecklenburg-Vorpommern",label:"Mecklenburg-Vorpommern" },{ value:"North Rhine-Westphalia",label:"North Rhine-Westphalia" },{ value:"Rhineland-Palatinate",label:"Rhineland-Palatinate" },{ value:"Saarland",label:"Saarland" },{ value:"Saxony",label:"Saxony" },{ value:"Saxony-Anhalt",label:"Saxony-Anhalt" },{ value:"Schleswig-Holstein",label:"Schleswig-Holstein" },{ value:"Thuringia",label:"Thuringia" },
  ],
  "France": [
    { value:"Auvergne-Rhône-Alpes",label:"Auvergne-Rhône-Alpes" },{ value:"Bourgogne-Franche-Comté",label:"Bourgogne-Franche-Comté" },{ value:"Brittany",label:"Brittany" },{ value:"Centre-Val de Loire",label:"Centre-Val de Loire" },{ value:"Corsica",label:"Corsica" },{ value:"Grand Est",label:"Grand Est" },{ value:"Hauts-de-France",label:"Hauts-de-France" },{ value:"Île-de-France",label:"Île-de-France" },{ value:"Normandy",label:"Normandy" },{ value:"Nouvelle-Aquitaine",label:"Nouvelle-Aquitaine" },{ value:"Occitanie",label:"Occitanie" },{ value:"Pays de la Loire",label:"Pays de la Loire" },{ value:"Provence-Alpes-Côte d'Azur",label:"Provence-Alpes-Côte d'Azur" },
  ],
  "Malaysia": [
    { value:"Johor",label:"Johor" },{ value:"Kedah",label:"Kedah" },{ value:"Kelantan",label:"Kelantan" },{ value:"Malacca",label:"Malacca" },{ value:"Negeri Sembilan",label:"Negeri Sembilan" },{ value:"Pahang",label:"Pahang" },{ value:"Penang",label:"Penang" },{ value:"Perak",label:"Perak" },{ value:"Perlis",label:"Perlis" },{ value:"Sabah",label:"Sabah" },{ value:"Sarawak",label:"Sarawak" },{ value:"Selangor",label:"Selangor" },{ value:"Terengganu",label:"Terengganu" },{ value:"Kuala Lumpur",label:"Kuala Lumpur",sub:"Federal Territory" },{ value:"Labuan",label:"Labuan",sub:"Federal Territory" },{ value:"Putrajaya",label:"Putrajaya",sub:"Federal Territory" },
  ],
  "China": [
    { value:"Beijing",label:"Beijing",sub:"Municipality" },{ value:"Chongqing",label:"Chongqing",sub:"Municipality" },{ value:"Shanghai",label:"Shanghai",sub:"Municipality" },{ value:"Tianjin",label:"Tianjin",sub:"Municipality" },{ value:"Guangdong",label:"Guangdong",sub:"Province" },{ value:"Jiangsu",label:"Jiangsu",sub:"Province" },{ value:"Shandong",label:"Shandong",sub:"Province" },{ value:"Zhejiang",label:"Zhejiang",sub:"Province" },{ value:"Sichuan",label:"Sichuan",sub:"Province" },{ value:"Fujian",label:"Fujian",sub:"Province" },{ value:"Hebei",label:"Hebei",sub:"Province" },{ value:"Hunan",label:"Hunan",sub:"Province" },{ value:"Anhui",label:"Anhui",sub:"Province" },{ value:"Hubei",label:"Hubei",sub:"Province" },{ value:"Liaoning",label:"Liaoning",sub:"Province" },{ value:"Shaanxi",label:"Shaanxi",sub:"Province" },{ value:"Jiangxi",label:"Jiangxi",sub:"Province" },{ value:"Yunnan",label:"Yunnan",sub:"Province" },{ value:"Heilongjiang",label:"Heilongjiang",sub:"Province" },{ value:"Henan",label:"Henan",sub:"Province" },{ value:"Guizhou",label:"Guizhou",sub:"Province" },{ value:"Gansu",label:"Gansu",sub:"Province" },{ value:"Hainan",label:"Hainan",sub:"Province" },{ value:"Xinjiang",label:"Xinjiang",sub:"Autonomous Region" },{ value:"Inner Mongolia",label:"Inner Mongolia",sub:"Autonomous Region" },{ value:"Guangxi",label:"Guangxi",sub:"Autonomous Region" },{ value:"Tibet",label:"Tibet",sub:"Autonomous Region" },{ value:"Ningxia",label:"Ningxia",sub:"Autonomous Region" },{ value:"Qinghai",label:"Qinghai",sub:"Province" },
  ],
  "Japan": [
    { value:"Hokkaido",label:"Hokkaido" },{ value:"Aomori",label:"Aomori" },{ value:"Iwate",label:"Iwate" },{ value:"Miyagi",label:"Miyagi" },{ value:"Akita",label:"Akita" },{ value:"Yamagata",label:"Yamagata" },{ value:"Fukushima",label:"Fukushima" },{ value:"Ibaraki",label:"Ibaraki" },{ value:"Tochigi",label:"Tochigi" },{ value:"Gunma",label:"Gunma" },{ value:"Saitama",label:"Saitama" },{ value:"Chiba",label:"Chiba" },{ value:"Tokyo",label:"Tokyo",sub:"Metropolis" },{ value:"Kanagawa",label:"Kanagawa" },{ value:"Niigata",label:"Niigata" },{ value:"Toyama",label:"Toyama" },{ value:"Ishikawa",label:"Ishikawa" },{ value:"Fukui",label:"Fukui" },{ value:"Yamanashi",label:"Yamanashi" },{ value:"Nagano",label:"Nagano" },{ value:"Shizuoka",label:"Shizuoka" },{ value:"Aichi",label:"Aichi" },{ value:"Mie",label:"Mie" },{ value:"Shiga",label:"Shiga" },{ value:"Kyoto",label:"Kyoto" },{ value:"Osaka",label:"Osaka" },{ value:"Hyogo",label:"Hyogo" },{ value:"Nara",label:"Nara" },{ value:"Wakayama",label:"Wakayama" },{ value:"Tottori",label:"Tottori" },{ value:"Shimane",label:"Shimane" },{ value:"Okayama",label:"Okayama" },{ value:"Hiroshima",label:"Hiroshima" },{ value:"Yamaguchi",label:"Yamaguchi" },{ value:"Fukuoka",label:"Fukuoka" },{ value:"Saga",label:"Saga" },{ value:"Nagasaki",label:"Nagasaki" },{ value:"Kumamoto",label:"Kumamoto" },{ value:"Oita",label:"Oita" },{ value:"Miyazaki",label:"Miyazaki" },{ value:"Kagoshima",label:"Kagoshima" },{ value:"Okinawa",label:"Okinawa" },
  ],
  "Singapore": [],
  "Hong Kong": [],
  "Maldives": [],
  "Bahrain": [],
  "Kuwait": [],
  "Qatar":   [{ value:"Doha",label:"Doha (Capital)" },{ value:"Al Wakrah",label:"Al Wakrah" },{ value:"Al Khor",label:"Al Khor" }],
  "Oman":    [{ value:"Muscat",label:"Muscat" },{ value:"Salalah",label:"Salalah" },{ value:"Sohar",label:"Sohar" }],
};

// ── Helpers ───────────────────────────────────────────────────────────────────
/** Returns state/province options for a given country, empty if none mapped. */
export function getStatesForCountry(country: string): SelectOption[] {
  return COUNTRY_STATES_MAP[country] ?? [];
}

/** Returns city options for a country+state combination. Falls back to INDIAN_CITIES for India with no state. */
export function getCitiesForState(country: string, state: string): SelectOption[] {
  if (country === "India") {
    return state ? (INDIA_STATE_CITIES_MAP[state] ?? []) : INDIAN_CITIES;
  }
  if (INTL_STATE_CITIES_MAP[country]) {
    return state ? (INTL_STATE_CITIES_MAP[country][state] ?? []) : [];
  }
  return [];
}

/** Returns the contextual label for the state/province field based on country. */
export function getStateLabel(country: string): string {
  switch (country) {
    case "United States":        return "State";
    case "Canada":               return "Province / Territory";
    case "United Arab Emirates": return "Emirate";
    case "Australia":            return "State / Territory";
    case "Germany":              return "Federal State";
    case "Japan":                return "Prefecture";
    case "China":                return "Province / Municipality";
    case "Saudi Arabia":         return "Region";
    default:                     return "State / Province";
  }
}
