#!/usr/bin/env bash
# =============================================================================
# push.sh — Run this FROM REPLIT to upload the latest build to the server.
#
# Usage:
#   chmod +x push.sh
#   ./push.sh
#
# What it touches:   ONLY /home/automystics-solarepc/htdocs/solarepc.automystics.tech/
# What it never does: PM2, nginx, systemd, or any other path.
# =============================================================================
set -euo pipefail

REMOTE_USER="root"
REMOTE_HOST="solarepc.automystics.tech"
REMOTE_PORT="${SSH_PORT:-22}"
REMOTE_DIR="/home/automystics-solarepc/htdocs/solarepc.automystics.tech"
SSH_KEY="/tmp/deploy-key/id_deploy"   # generated by Replit; valid this session only

RSYNC="rsync -az --checksum --delete \
  -e \"ssh -i $SSH_KEY -p $REMOTE_PORT -o StrictHostKeyChecking=accept-new\""

echo "▶ Pushing ERP frontend (public/)..."
eval "$RSYNC" \
  "$(dirname "$0")/public/" \
  "${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR}/public/"

echo "▶ Pushing API server dist/..."
eval "$RSYNC" \
  "$(dirname "$0")/api-server/dist/" \
  "${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR}/api-server/dist/"

echo "▶ Pushing API package.json (production deps)..."
rsync -az \
  -e "ssh -i $SSH_KEY -p $REMOTE_PORT -o StrictHostKeyChecking=accept-new" \
  "$(dirname "$0")/api-server/package.json" \
  "${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR}/api-server/package.json"

echo "✓ Files uploaded to ${REMOTE_DIR}"
echo ""
echo "Next — run on the server:"
echo "  cd ${REMOTE_DIR} && bash deploy/deploy.sh"
