import { Router, type IRouter } from "express";
import { requireAuth } from "../lib/rbac";
import healthRouter from "./health";
import storageRouter from "./storage";
import procQuotationAttachmentsRouter from "./proc_quotation_attachments";
import authRouter from "./auth";
import dashboardRouter from "./dashboard";
import leadsRouter from "./leads";
import quotationsRouter from "./quotations";
import crmInvoicesRouter from "./crm-invoices";
import tasksRouter from "./tasks";
import escalationsRouter from "./escalations";
import projectsRouter from "./projects";
import procurementRouter from "./procurement";
import inventoryRouter from "./inventory";
import engineeringRouter from "./engineering";
import commissioningRouter from "./commissioning";
import oamRouter from "./oam";
import vendorsRouter from "./vendors";
import materialsRouter from "./materials";
import procQuotationsRouter from "./proc_quotations";
import procPOsRouter from "./proc_pos";
import procGRNsRouter from "./proc_grns";
import procInvoicesRouter from "./proc_invoices";
import procDashboardRouter from "./proc_dashboard";
import notificationsRouter from "./notifications";
import grnReturnsRouter from "./grn_returns";
import stockTransfersRouter from "./stock_transfers";
import reportsRouter from "./reports";
import usersRouter from "./users";
import approvalsRouter from "./approvals";
import rbacRouter from "./rbac";
import solarInventoryRouter from "./solar_inventory";
import projLifecycleRouter from "./proj_lifecycle";
import projExecutionRouter from "./proj_execution";
import projClosureRouter from "./proj_closure";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use(procQuotationAttachmentsRouter);
router.use(authRouter);
// Catch-all auth guard — any future router that omits requireAuth is still protected
router.use(requireAuth());
router.use(dashboardRouter);
router.use(leadsRouter);
router.use(quotationsRouter);
router.use(crmInvoicesRouter);
router.use(tasksRouter);
router.use(escalationsRouter);
router.use(projectsRouter);
router.use(procurementRouter);
router.use(inventoryRouter);
router.use(engineeringRouter);
router.use(commissioningRouter);
router.use(oamRouter);
router.use(vendorsRouter);
router.use(materialsRouter);
router.use(procQuotationsRouter);
router.use(procPOsRouter);
router.use(procGRNsRouter);
router.use(procInvoicesRouter);
router.use(procDashboardRouter);
router.use(notificationsRouter);
router.use(grnReturnsRouter);
router.use(stockTransfersRouter);
router.use(reportsRouter);
router.use(usersRouter);
router.use(approvalsRouter);
router.use(rbacRouter);
router.use(solarInventoryRouter);
router.use(projLifecycleRouter);
router.use(projExecutionRouter);
router.use(projClosureRouter);

export default router;
